[clipboardresize]
holdtime=3000
holdtimeshort=2000
holdtimelong=6000

[hotkeys]
menuHotkey="+#z"
exitHotkey="+!#z"
captureAndResizeHotkey="#z"
captureAndResizeSaveHotkey="^#z"
setsizeValuesHotkey="!#z"
ocrHotkey="#y"

[config]
font="Calibri"
fontsize=10
guiWidth=590
guiHeight=500
internalPreviewWidth=560
interalPreviewHeight=390
clipboardBeepSound="clipboard.mp3"

[image]
showresized=yes
targetwidth=800
targetheight=600

[external]
;filemanager="C:\Windows\explorer.exe"

[operation]
automode=1
